// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://waljziyxcblsnsyoqoco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhbGp6aXl4Y2Jsc25zeW9xb2NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NjM4NzcsImV4cCI6MjA3MzQzOTg3N30.-iKE4Z7NIeA1Tlb6zYQNVT42tBmwBm11KqA_eEiO3SM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});